### ISSUE TITLE
Need help in creating site graph json file 

### ISSUE THREAD

**Issue by ksingh-scogo** [TransformerOptimus/AutoNode#9]
@MananX @Akki-jain @ngaurav

First of all , thanks for making AutoNode OpenSource , this looks a very sexy project

Just realised that i am the first person to raise the very first issue, need some guidance on creating site graph creation , how to create if for any website ?

Suppose i want to scrape the name  from https://github.com/trending  > Go to every project and > get the string from the About section. How can i achieve this.  Would be great if you can give an example of creating the site graph json 

- From the example in readme , from where does the location [100, 200] will come ? 

```
{
    "1": {
        "node_type": "clickable_and_typeable",
        "node_name": "Login Button",
        "actionable_element_type": "button",
        "location": [100, 200],
        "is_type": false,
        "adjacent_to": ["2"]
    },
    "2": {
        "node_type": "clickable_and_typeable",
        "node_name": "Username Field",
        "actionable_element_type": "textbox",
        "location": [150, 250],
        "is_type": true,
        "type_description": "Enter username here",
        "adjacent_to": []
    }
}
```

**Comment by ksingh-scogo** [comment]
BTW i tried executing 

```
curl -X 'POST' \
  'http://localhost:8002/api/yolo/image/detect' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'image=@image1.png;type=image/png'
```

however got the below error

```
backend-1   | WARNING:  WatchFiles detected changes in 'yolo/yolo/configs/settings.py'. Reloading...
backend-1   | INFO:     Shutting down
backend-1   | INFO:     Waiting for application shutdown.
backend-1   | INFO:     Application shutdown complete.
backend-1   | INFO:     Finished server process [18]
backend-1   | INFO:     Started server process [20]
backend-1   | INFO:     Waiting for application startup.
backend-1   | INFO:     Application startup complete.
yolo-1      | [2024-05-31 18:32:04 +0000] [9] [ERROR] Exception in ASGI application
yolo-1      | Traceback (most recent call last):
yolo-1      |   File "/venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
yolo-1      |     result = await app(  # type: ignore[func-returns-value]
yolo-1      |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yolo-1      |   File "/venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
yolo-1      |     return await self.app(scope, receive, send)
yolo-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yolo-1      |   File "/venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
yolo-1      |     await super().__call__(scope, receive, send)
yolo-1      |   File "/venv/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
yolo-1      |     await self.middleware_stack(scope, receive, send)
yolo-1      |   File "/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
yolo-1      |     raise exc
yolo-1      |   File "/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
yolo-1      |     await self.app(scope, receive, _send)
yolo-1      |   File "/venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
yolo-1      |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
yolo-1      |   File "/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
yolo-1      |     raise exc
yolo-1      |   File "/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
yolo-1      |     await app(scope, receive, sender)
yolo-1      |   File "/venv/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
yolo-1      |     await self.middleware_stack(scope, receive, send)
yolo-1      |   File "/venv/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
yolo-1      |     await route.handle(scope, receive, send)
yolo-1      |   File "/venv/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
yolo-1      |     await self.app(scope, receive, send)
yolo-1      |   File "/venv/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
yolo-1      |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
yolo-1      |   File "/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
yolo-1      |     raise exc
yolo-1      |   File "/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
yolo-1      |     await app(scope, receive, sender)
yolo-1      |   File "/venv/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
yolo-1      |     response = await func(request)
yolo-1      |                ^^^^^^^^^^^^^^^^^^^
yolo-1      |   File "/venv/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
yolo-1      |     raw_response = await run_endpoint_function(
yolo-1      |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yolo-1      |   File "/venv/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
yolo-1      |     return await dependant.call(**values)
yolo-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yolo-1      |   File "/app/yolo/yolo/controllers/image_controller.py", line 10, in detect_object
yolo-1      |     result = YoloService().detect(await image.read())
yolo-1      |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yolo-1      |   File "/app/yolo/yolo/services/yolo_service.py", line 18, in detect
yolo-1      |     boxes, bbox_class_name = ModelService(model_type=self.model_type).predict(image_obj, image_contents)
yolo-1      |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yolo-1      |   File "/app/yolo/yolo/services/model_service.py", line 32, in predict
yolo-1      |     return self._remote_predict(image_contents)
yolo-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yolo-1      |   File "/app/yolo/yolo/services/model_service.py", line 91, in _remote_predict
yolo-1      |     response = requests.post(config.yolo_remote_url, headers=headers, json=payload)
yolo-1      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yolo-1      |   File "/venv/lib/python3.12/site-packages/requests/api.py", line 115, in post
yolo-1      |     return request("post", url, data=data, json=json, **kwargs)
yolo-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yolo-1      |   File "/venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
yolo-1      |     return session.request(method=method, url=url, **kwargs)
yolo-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yolo-1      |   File "/venv/lib/python3.12/site-packages/requests/sessions.py", line 575, in request
yolo-1      |     prep = self.prepare_request(req)
yolo-1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^
yolo-1      |   File "/venv/lib/python3.12/site-packages/requests/sessions.py", line 484, in prepare_request
yolo-1      |     p.prepare(
yolo-1      |   File "/venv/lib/python3.12/site-packages/requests/models.py", line 367, in prepare
yolo-1      |     self.prepare_url(url, params)
yolo-1      |   File "/venv/lib/python3.12/site-packages/requests/models.py", line 438, in prepare_url
yolo-1      |     raise MissingSchema(
yolo-1      | requests.exceptions.MissingSchema: Invalid URL '<YOLO_REMOTE_URL>': No scheme supplied. Perhaps you meant https://<YOLO_REMOTE_URL>?
```

**Comment by MananX** [comment]
Hey Karan, thanks for using and wishing to contribute to AutoNode.
From the error logs it seems like you have set USE_REMOTE_YOLO to True in
either your .env or settings.py in the yolo directory. You should set that
to True when you wish to host the yolo and ocr codes remotely on a cloud
server by yourself to use cloud resources.
If you wish to run yolo and ocr locally, the USE_REMOTE_YOLO/OCR should be
set to false in .env for that particular directory and the default in
settings.py for that directory should also be false.

Thankyou!

**Comment by MistaahJ** [comment]
> @MananX @Akki-jain @ngaurav
> 
> First of all , thanks for making AutoNode OpenSource , this looks a very sexy project
> 
> Just realised that i am the first person to raise the very first issue, need some guidance on creating site graph creation , how to create if for any website ?
> 
> Suppose i want to scrape the name from https://github.com/trending > Go to every project and > get the string from the About section. How can i achieve this. Would be great if you can give an example of creating the site graph json
> 
> * From the example in readme , from where does the location [100, 200] will come ?
> 
> ```
> {
>     "1": {
>         "node_type": "clickable_and_typeable",
>         "node_name": "Login Button",
>         "actionable_element_type": "button",
>         "location": [100, 200],
>         "is_type": false,
>         "adjacent_to": ["2"]
>     },
>     "2": {
>         "node_type": "clickable_and_typeable",
>         "node_name": "Username Field",
>         "actionable_element_type": "textbox",
>         "location": [150, 250],
>         "is_type": true,
>         "type_description": "Enter username here",
>         "adjacent_to": []
>     }
> }
> ```

Thanks for raising the issue on Site-graph creation. A site graph, in its simplest essence is a json file which reduces the sample space of actions for the AutoNode. The site graph involves parent nodes and their possible children nodes on the basis of actions taken during workflow(s) within a site. Site graph creation could either be facilitated using the developer tools available to extract relevant selectors for a node (node_name, actionable_element_type, location) or using a custom script to record actions within a sample workflow and post processing to obtain relevant information (description, type_description, and relevant flags).

NOTE : Here location is an instance of resolution percentages and not absolute pixel location of the element within the screen resolution. You may refer site-graphs and templates provided.

The site-graph for your use case may look like :
```
{
    "1": {
        "node_type": "planning",
        "node_name": "Planning Node",
        "description": "Plan the execution on the website. Extract the execution in steps explaining the LLM how to proceed",
        "planning_prompt": "<Your planning prompt>",
        "adjacent_from": [],
        "adjacent_to": [2]
    },
    "2": {
        "node_type": "navigation",
        "node_name": "github-trending-navigation",
        "url": "https://github.com/trending",
        "description": "You can choose this node to navigate to the page to see what's trending on GitHub community",
        "adjacent_from": [1],
        "adjacent_to": [3,4]
    },
    "3": {
        "node_type": "clickable_and_typeable",
        "node_name": "Repositories",
        "actionable_element_type": "button",
        "location": [22.15, 44.45],
        "description": "You can choose this button to view the trending GitHub repositories"
        "is_type": false,
        "adjacent_to": [5,...]
    },
    "4": {
        "node_type": "clickable_and_typeable",
        "node_name": "Developers",
        "actionable_element_type": "button",
        "location": [26.25, 44.45],
        "is_type": false,
        "description": "You can choose this button to view the trending GitHub developers",
        "adjacent_to": [6,...]
    },
    ...
}
```

**Comment by gunar** [comment]
> Site graph creation could either be facilitated using the developer tools available to extract relevant selectors for a node (node_name, actionable_element_type, location) or using a custom script to record actions within a sample workflow and post processing to obtain relevant information (description, type_description, and relevant flags).

Can you elaborate on this?

> NOTE : Here location is an instance of resolution percentages and not absolute pixel location of the element within the screen resolution. You may refer site-graphs and templates provided.

What's the most ergonomic way to get a given element's location (in percentages)?
